[package]
name = "rust-livescore"
version = "0.1.0"
authors = ["Ward Muylaert <ward.muylaert@gmail.com>"]
edition = "2018"

[lib]
name = "livescore"
path = "src/lib.rs"

[[bin]]
name = "rust-livescore-bin"
path = "src/main.rs"

[dependencies]
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
